# Generated by Django 6.0.3 on 2026-03-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
