# Generated by Django 6.0.3 on 2026-03-11 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_account_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='clean_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='MerchantEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=255, unique=True)),
                ('clean_name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.category')),
            ],
        ),
    ]
